### ISSUE TITLE
Can't transcript

### ISSUE THREAD

**Issue by thvi** [muratali016/Youtube_AI_Detective#1]
Failed to fetch transcript: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=sP-21AqAHKw! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en', 'tr', 'de']

For this video (sP-21AqAHKw) transcripts are available in the following languages:

(MANUALLY CREATED)
None

(GENERATED)
 - fr ("Français (générés automatiquement)")[TRANSLATABLE]

(TRANSLATION LANGUAGES)
 - af ("Afrikaans")
 - ak ("Akan")
 - sq ("Albanais")
 - de ("Allemand")
 - am ("Amharique")
 - en ("Anglais")
 - ar ("Arabe")
 - hy ("Arménien")
 - as ("Assamais")
 - ay ("Aymara")
 - az ("Azerbaïdjanais")
 - eu ("Basque")
 - bn ("Bengali")
 - bho ("Bhodjpouri")
 - be ("Biélorusse")
 - my ("Birman")
 - bs ("Bosniaque")
 - bg ("Bulgare")
 - ca ("Catalan")
 - ceb ("Cebuano")
 - ny ("Chewa")
 - zh-Hans ("Chinois (Simplifié)")
 - zh-Hant ("Chinois (Traditionnel)")
 - si ("Cingalais")
 - ko ("Coréen")
 - co ("Corse")
 - ht ("Créole Haïtien")
 - hr ("Croate")
 - da ("Danois")
 - es ("Espagnol")
 - eo ("Espéranto")
 - et ("Estonien")
 - ee ("Éwé")
 - fil ("Filipino")
 - fi ("Finnois")
 - fr ("Français")
 - fy ("Frison Occidental")
 - gd ("Gaélique Écossais")
 - gl ("Galicien")
 - cy ("Gallois")
 - lg ("Ganda")
 - ka ("Géorgien")
 - gu ("Goudjarati")
 - el ("Grec")
 - gn ("Guarani")
 - ha ("Haoussa")
 - haw ("Hawaïen")
 - iw ("Hébreu")
 - hi ("Hindi")
 - hmn ("Hmong")
 - hu ("Hongrois")
 - ig ("Igbo")
 - id ("Indonésien")
 - ga ("Irlandais")
 - is ("Islandais")
 - it ("Italien")
 - ja ("Japonais")
 - jv ("Javanais")
 - kn ("Kannada")
 - kk ("Kazakh")
 - km ("Khmer")
 - rw ("Kinyarwanda")
 - ky ("Kirghize")
 - kri ("Krio")
 - ku ("Kurde")
 - lo ("Lao")
 - la ("Latin")
 - lv ("Letton")
 - ln ("Lingala")
 - lt ("Lituanien")
 - lb ("Luxembourgeois")
 - mk ("Macédonien")
 - ms ("Malais")
 - ml ("Malayalam")
 - dv ("Maldivien")
 - mg ("Malgache")
 - mt ("Maltais")
 - mi ("Maori")
 - mr ("Marathi")
 - mn ("Mongol")
 - nl ("Néerlandais")
 - ne ("Népalais")
 - no ("Norvégien")
 - or ("Odia")
 - om ("Oromo")
 - ug ("Ouïghour")
 - ur ("Ourdou")
 - uz ("Ouzbek")
 - ps ("Pachto")
 - pa ("Pendjabi")
 - fa ("Persan")
 - pl ("Polonais")
 - pt ("Portugais")
 - qu ("Quechua")
 - ro ("Roumain")
 - ru ("Russe")
 - sm ("Samoan")
 - sa ("Sanskrit")
 - sr ("Serbe")
 - sn ("Shona")
 - sd ("Sindhi")
 - sk ("Slovaque")
 - sl ("Slovène")
 - so ("Somali")
 - nso ("Sotho Du Nord")
 - st ("Sotho Du Sud")
 - su ("Soundanais")
 - sv ("Suédois")
 - sw ("Swahili")
 - tg ("Tadjik")
 - ta ("Tamoul")
 - tt ("Tatar")
 - cs ("Tchèque")
 - te ("Télougou")
 - th ("Thaï")
 - ti ("Tigrigna")
 - ts ("Tsonga")
 - tr ("Turc")
 - tk ("Turkmène")
 - uk ("Ukrainien")
 - vi ("Vietnamien")
 - xh ("Xhosa")
 - yi ("Yiddish")
 - yo ("Yoruba")
 - zu ("Zoulou")

If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!

**Comment by muratali016** [comment]
Hi @thvi , I have added only the languages that I speak. If you want to receive also transcript in French, you can add 'fr' in line 223 in main.py 
transcript = transcript_list.find_transcript(['en', 'tr', 'de'])
